apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-cbaapp
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /data/mysql-cbaapp
