apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: cba-connect
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "DUMMY"
  MYSQL_DATABASE: "cbaapp"
  MYSQL_USER: "cba"
  MYSQL_PASSWORD: "DUMMY"
  TZ: "Asia/Seoul"
  MYSQL_INITDB_SKIP_TZINFO: "1"
